/*                             == SAVE AND LOAD ==                                  */

load_game(Namafile):-
	/*load file */

	open(Namafile, read, Stream),

    /*variabel global player*/
	isPlay,
	exp(Exp),
	level(Level),
	gold(Gold),
	attack(Attack),
	defense(Defense),
	attInv(AttInv),
	defInv(DefInv),
	health(Health),
	batasExp(BatasExp),
	batasHP(BatasHP),
	job(Job),
	amount(Amount),
	noQuest,
	adaQuest,
	quest(Quest1,Quest2,Quest3),
	enemy(Enemy1,Enemy2,Enemy3),

	retract(isPlay),
	retract(exp(Exp)),
	retract(level(Level)),
	retract(gold(Gold)),
	retract(attack(Attack)),
	retract(defense(Defense)),
	retract(attInv(AttInv)),
	retract(defInv(DefInv)),
	retract(health(Health)),
	retract(batasExp(BatasExp)),
	retract(batasHP(BatasHP)),
	retract(job(Job)),
	retract(amount(Amount)),
	retract(noQuest),
	retract(adaQuest),
	retract(quest(Quest1,Quest2,Quest3)),
	retract(enemy(Enemy1,Enemy2,Enemy3)),


	/* membaca  data  player*/
	read(Stream, New_Exp),
	read(Stream, New_Level),
	read(Stream, New_Gold),
	read(Stream, New_Attack),
	read(Stream, New_Defense),
	read(Stream, New_AttInv),
	read(Stream, New_DefInv),
	read(Stream, New_Health),
	read(Stream, New_BatasExp),
	read(Stream, New_BatasHP),
	read(Stream, New_Job),
	read(Stream, New_Amount),
	read(Stream, New_Quest1),
	read(Stream, New_Quest2),
	read(Stream, New_Quest3),
	read(Stream, New_Enemy1),
	read(Stream, New_Enemy2),
	read(Stream, New_Enemy3),


	asserta(isPlay),
	asserta(exp(New_Exp)),
	asserta(level(New_Level)),
	asserta(gold(New_Gold)),
	asserta(attack(New_Attack)),
	asserta(defense(New_Defense)),
	asserta(attInv(New_AttInv)),
	asserta(defInv(New_DefInv)),
	asserta(health(New_Health)),
	asserta(batasExp(New_BatasExp)),
	asserta(batasHP(New_BatasHP)),
	asserta(job(New_Job)),
	asserta(amount(New_Amount)),
	asserta(noQuest),
	asserta(adaQuest),
	asserta(quest(New_Quest1,New_Quest2,New_Quest3)),
	asserta(enemy(New_Enemy1,New_Enemy2,New_Enemy3)),


    /*variabel global map*/
	panjangMap(a),
	lebarMap(a),
	musuh(a,b),
	battle(a),
	banyakMusuh(a),
	storePosition(a),
	questPosition(a),
	dungeonPosition(a),
	playerPosition(a),
	getStore,
	noMap,

	retract(panjangMap(a)),
	retract(lebarMap(a)),
	retract(musuh(a,b)),
	retract(battle(a)),
	retract(banyakMusuh(a)),
	retract(storePosition(a)),
	retract(questPoistion(a)),
	retract(dungeonPosition(a)),
	retract(playerPosition(a)),
	retract(getStore),
	retract(noMap),

	read(Stream, new_panjangMap),
    read(Stream, new_lebarMap),
	read(Stream, new_nama),
	read(Stream, new_posisi),
	read(Stream, new_battle),
	read(Stream, new_banyakMusuh),
	read(Stream, new_storePosition),
	read(Stream, new_questPosition),
	read(Stream, new_dungeonPosition),
	read(Stream, new_playerPosition),

	asserta(panjangMap(new_panjangMap)),
	asserta(lebarMap(new_lebarMap)),
	asserta(musuh(new_nama,new_posisi)),
	asserta(battle(new_battle)),
	asserta(banyakMusuh(new_banyakMusuh)),
	asserta(storePosition(new_Position)),
	asserta(questPosition(new_questPosition)),
	asserta(dungeonPosition(new_dungeonPosition)),
	asserta(playerPosition(new_playerPosition)),
	asserta(getStore),
	asserta(noMap),

	/*variabel global musuh(enemy)*/
	enemyHP(EnemyHP),
    enemyAtk(EnemyAtk),
    enemyDfs(EnemyDfs),
    enemyExp(EnemyExp),
    isBattle,

    retract(enemyHP(EnemyHP)),
    retract(enemyAtk(EnemyAtk)),
    retract(enemyDfs(EnemyDfs)),
    retract(enemyExp(EnemyExp)),
	retract(isBattle),

    /*membaca data musuh(enemy)*/
    read(Stream, New_EnemyHP),
    read(Stream, New_EnemyAtk),
    read(Stream, New_EnemyDfs),
	read(Stream, New_EnemyExp),

    asserta(enemyHP(New_EnemyHP)),
    asserta(enemyAtk(New_EnemyAtk)),
    asserta(enemyDfs(New_EnemyDfs)),
    asserta(enemyExp(New_EnemyExp)),
   	asserta(isBattle),

    write('Data has been  successfully loaded!'), nl,
	close(Stream).



save_game(namafile):-
	/* save file */

	open(namafile, write, Stream),

	/* data yang terkumpul */
	isPlay,
	exp(Exp),
	level(Level),
	gold(Gold),
	attack(Attack),
	defense(Defense),
	attInv(AttInv),
	defInv(DefInv),
	health(Health),
	batasExp(BatasExp),
	batasHP(BatasHP),
	job(Job),
	amount(Amount),
	noQuest,
	adaQuest,
	quest(Quest1,Quest2,Quest3),
	enemy(Enemy1,Enemy2,Enemy3),


	panjangMap(PanjangMap),
	lebarMap(LebarMap),
	musuh(Nama,[X,Y]),
	battle(Battle),
	banyakMusuh(BanyakMusuh),
	storePosition(StorePosition),
	questPosition(QuestPosition),
	dungeonPosition(DungeonPosition),
	playerPosition(PlayerPosition),
	getStore,
	noMap,

	enemyHP(EnemyHP),
    enemyAtk(EnemyAtk),
    enemyDfs(EnemyDfs),
    enemyExp(EnemyExp),
    isBattle,

	/* menulis data player */
	write(Stream, Exp), 			write(Stream, '.'), nl(Stream),
	write(Stream, Level), 			write(Stream, '.'), nl(Stream),
	write(Stream, Gold), 			write(Stream, '.'), nl(Stream),
	write(Stream, Attack), 			write(Stream, '.'), nl(Stream),
	write(Stream, Defense), 		write(Stream, '.'), nl(Stream),
	write(Stream, AttInv), 			write(Stream, '.'), nl(Stream),
	write(Stream, DefInv), 		    write(Stream, '.'), nl(Stream),
    write(Stream, Health), 		    write(Stream, '.'), nl(Stream),
    write(Stream, BatasExp), 		write(Stream, '.'), nl(Stream),
    write(Stream, BatasHP), 		write(Stream, '.'), nl(Stream),
    write(Stream, Job), 		    write(Stream, '.'), nl(Stream),
    write(Stream, Amount), 		    write(Stream, '.'), nl(Stream),
    write(Stream, Quest1), 		    write(Stream, '.'), nl(Stream),
    write(Stream, Quest2), 		    write(Stream, '.'), nl(Stream),
    write(Stream, Quest3), 		    write(Stream, '.'), nl(Stream),
    write(Stream, Enemy1), 		    write(Stream, '.'), nl(Stream),
    write(Stream, Enemy2), 		    write(Stream, '.'), nl(Stream),
    write(Stream, Enemy3), 		    write(Stream, '.'), nl(Stream),

	/* menulis data map */
	write(Stream, PanjangMap), 		write(Stream, '.'), nl(Stream),
	write(Stream, LebarMap), 		write(Stream, '.'), nl(Stream),
	write(Stream, Nama), 		    write(Stream, '.'), nl(Stream),
	write(Stream, [X,Y]), 		    write(Stream, '.'), nl(Stream),
	write(Stream, Battle), 	    	write(Stream, '.'), nl(Stream),
	write(Stream, BanyakMusuh), 	write(Stream, '.'), nl(Stream),
	write(Stream, StorePosition), 	write(Stream, '.'), nl(Stream),
	write(Stream, QuestPosition), 	write(Stream, '.'), nl(Stream),
	write(Stream, DungeonPosition),	write(Stream, '.'), nl(Stream),
	write(Stream, PlayerPosition), 	write(Stream, '.'), nl(Stream),

	/*menulis data musuh(enemy)*/
	write(Stream, EnemyHP), 		write(Stream, '.'), nl(Stream),
	write(Stream, EnemyAtk), 		write(Stream, '.'), nl(Stream),
	write(Stream, EnemyDfs), 		    write(Stream, '.'), nl(Stream),
	write(Stream, EnemyExp), 		    write(Stream, '.'), nl(Stream),

	write('Data has been saved successfully !'), nl,
	close(Stream).
